# Look at Semantic Scholar Courpus Data

In [3]:
%load_ext autoreload
%autoreload 2
%reload_ext autoreload

%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import h5py
from pathlib import Path

from importlib.util import find_spec
if find_spec("similarity_abstract_search") is None:
    import sys
    sys.path.append('..')
    
from similarity_abstract_search.datasets.dataset import SemanticCorpusDataset  
from similarity_abstract_search import utils

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [4]:
Path.ls = lambda x: list(x.iterdir())

In [5]:
data_dir =  Path('../../Data/processed/')
data_dir.ls()


[PosixPath('../../Data/processed/paperID2emb.json'),
 PosixPath('../../Data/processed/embedIDs.h5'),
 PosixPath('../../Data/processed/paper_set.txt'),
 PosixPath('../../Data/processed/SemanticScholarData'),
 PosixPath('../../Data/processed/manifest.txt')]

In [6]:
data_fn = (data_dir/'SemanticScholarData').ls()
fn = data_fn[0]
print(fn)
data_fn[:3]

../../Data/processed/SemanticScholarData/pruned_and_clean103.json


[PosixPath('../../Data/processed/SemanticScholarData/pruned_and_clean103.json'),
 PosixPath('../../Data/processed/SemanticScholarData/pruned_and_clean088.json'),
 PosixPath('../../Data/processed/SemanticScholarData/pruned_and_clean047.json')]

In [7]:
inner_path = str(data_dir/'SemanticScholarData')


In [77]:
data = SemanticCorpusDataset()

In [78]:
data.load_one_batch()

id  \
EmbeddingID                                             
10291659     3b9b9509bb4eea4711515a40a7f210d8561487aa   
13584557     c4c1d7a8051a5ee1562dc8b5722c3353b8d7e226   
9811857      e300444162aa59fe05c18f99e36db8a1125275c3   
764869       57c98b205d48d605f17d884bd6abe9a66c846989   
10295489     e316c2902c421370001baf099e439cf68bef62fa   
...                                               ...   
13139466     10e10bb1a46166152458e1959eadab88ab604d3d   
707527       e0ae60948a24dfa0e6296effb7750c00391f7d46   
9324370      99d8a0df8507fc78e3a8cf4cc68bb3134a4d4b20   
9802191      7983389420ea39ec8dc8440b921319e1d154601e   
9214270      3a4b5e3ece7dbeefc5e1664ea6a078e60c822f99   

                                                 paperAbstract  \
EmbeddingID                                                      
10291659     Anterior segment dysgeneses are developmental ...   
13584557     The first synthesis of dolabelide C (1), a cyt...   
9811857      BACKGROUND & AIMS: Helicobacter pylori eradica...   
764869       BACKGROUND\nMinorities are more prevalent than...   
10295489     Today, many tetraplegics benefit from surgical...   
...                                                        ...   
13139466     'Metadata' has received a fraction of the atte...   
707527       OBJECTIVES\nTo describe average levels of free...   
9324370      I N VIVO confocal laser scanning microscopy (C...   
9802191      INTRODUCTION\nCongenital tuberculosis is a rar...   
9214270      Development of sporangia in Phytophthora palmi...   

                                                         title  \
EmbeddingID                                                      
10291659     The 6p25 deletion syndrome: An update on a rar...   
13584557     Total synthesis of dolabelide C: a phosphate-m...   
9811857      Effects of Community Screening for Helicobacte...   
764869       Racial and ethnic disparities in physical abus...   
10295489     New concepts on treatment of the upper limb in...   
...                                                        ...   
13139466     Metadata accounts: Achieving data and evidence...   
707527       Human energy expenditure in affluent societies...   
9324370      The vascular features of psoriatic skin: imagi...   
9802191      Analysis of 170 cases of congenital TB reporte...   
9214270      Growth and ultrastructural differentiation of ...   

                                              citeEmbeddingsID  
EmbeddingID                                                     
10291659     [12279879, 11377917, 10611622, 4885766, 671395...  
13584557                                             [5007102]  
9811857      [9936039, 1851207, 446836, 11518128, 9864285, ...  
764869                                       [6924879, 457180]  
10295489      [7564871, 10920400, 13471692, 3174646, 10921211]  
...                                                        ...  
13139466                                             [2442410]  
707527       [1997359, 11775545, 7111644, 86053, 3490113, 1...  
9324370      [11362903, 12617902, 8475976, 12960323, 257405...  
9802191      [3540689, 12109320, 10107597, 983278, 9470101,...  
9214270                                              [3672511]  

[64 rows x 4 columns]

In [79]:
data.show_data()

Title is : Population studies and validation of paternity determinations by six microsatellite loci.
Abstract is : A single locus system of 6 microsatellite markers was evaluated for paternity testing. A nonradioactive method based on peroxidase labeling of a DNA probe was used to estimate the allele frequency of markers D1S216, D3S1217, D7S480, D9S157, D13S153, and D16S422 by genotyping 1134-1698 chromosomes. The number of detected alleles were 22, 15, 23, 10, 16, and 19, respectively, and the allele frequency varied from 0.001 to 0.317. The genotype of 87 families, consisting of mother, father, and child was determined. The probability that a random individual will give a positive paternity was evaluated. We conclude that the markers can be reliably typed and give sufficient and reliable information for paternity testing.
Link is :  https://www.semanticscholar.org/paper/7d9addb22565ebf79a19b1a77683d33ff0663f7d


In [15]:
h5file = utils.loadH5file(data_dir/'embedIDs.h5')
trainData = np.column_stack(( h5file['paper' ][:] , h5file['cites' ][:] ))

In [25]:
h5file['paper'][:4], h5file['cites'][:4]

(array([10291659, 13584557,  9811857,   764869], dtype=int32),
 array([array([12279879, 11377917, 10611622,  4885766,  6713959, 11472980,
         4985806,  5487724,   684838, 13727658,  7407284,  3248404,
         4723212,  5442396,  5061212, 10502502,  9808902,  8182254,
         9085600,  3028060,  9996880,  9661559, 11418460,  9824852,
         8882707,  8722993], dtype=int32),
        array([5007102], dtype=int32),
        array([ 9936039,  1851207,   446836, 11518128,  9864285,  6948941,
        12636073,  1527052, 11381674,  8982488,  6955016], dtype=int32),
        array([6924879,  457180], dtype=int32)], dtype=object))

In [26]:
trainData.shape

(13786318, 2)